lib/as3/tokenizer.lex
=> fix a match bug in MULTILINE_COMMENT

src/gif2swf.c
API changed for DGifCloseFile:
http://sourceforge.net/p/giflib/code/ci/116179a7d4681dda9afcdd43b5fbfb391b44918b/tree/doc/gif_lib.xml?diff=8408b09b69e5ce836d01a29e05c626ffa55cffaa
=> Fix "too few arguments to function ‘DGifCloseFile’"

lib/pdf/xpdf-changes.patch
This patch fixes a Use After Free vulnerability in the xpdf code used by swftools.
=> Patch for CVE-2017-7698

lib/modules/swfshape.c
fillstyleadd and linestyleadd can be changed when styles change happen.
Add them later and only if style is non-zero.
=> fix shape parsing after styles change

src/swfextract.c
With this patch it is possible to extract a sound with an unknown format number, rather than silently exiting which is unhelpful behaviour.
=> don't silently exit on unknown sound format

lib/lame/vbrquantize.c
- https://en.cppreference.com/w/c/language/inline
```
Any function with internal linkage may be declared static inline with no other restrictions.
A non-static inline function cannot define a non-const function-local static and cannot refer to a file-scope static.
```
Failure on macOS build.
```
Undefined symbols for architecture x86_64:
"_compute_scalefacs_long", referenced from:
_long_block_scalefacs in librfxswf.a(vbrquantize.o)
"_compute_scalefacs_long_lsf", referenced from:
_long_block_scalefacs in librfxswf.a(vbrquantize.o)
"_compute_scalefacs_short", referenced from:
_short_block_scalefacs in librfxswf.a(vbrquantize.o)
"_find_scalefac_ave", referenced from:
_short_block_sf in librfxswf.a(vbrquantize.o)
_long_block_sf in librfxswf.a(vbrquantize.o)
"_find_scalefac_mq", referenced …
```
=> "Inline" should be prefixed with static/external modifier.

lib/modules/swfbits.c
Solution suggestions for CVE-2017-16711
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-16711
ref) https://github.com/matthiaskramm/swftools/issues/46
- swftools/lib/modules/swfbits.c
swf_DefineLosslessBitsTagToImage extract zlib compressed imagedata(RGBA)
swf_JPEG2TagToImage extracts zlib compressed alphadata(A) from JPEG3 tag.
If these functions fail to inflate a zlib compressed RGBA(or A) array, return NULL as an RGBA array.
and users of the RGBA array reference it without NULL checking, causing a segmentation fault.
swfbits must be continue processing even if zlib infrate of image fails.
CVE-2017-16711 will be superficially resolved.
If we want to be more secure, we need to add a NULL check to the code that references the RGBA array pointer. We should discuss this in a …
=> swfbits must be continue processing even if zlib infrate of image fails.

lib/modules/swfbits.c
#46 was not enough care. I will fix it additionally.
For #46, the behavior has been changed so that processing continues even if inflation is incomplete.
With rfx_alloc(malloc wrapper),  the possibility of displaying uninitialized data remains.
Should be changed to rfx_calloc(calloc wrapper).
=> change rfx_alloc to rfx_calloc for Lossless RGBA, JPEG3 alpha zlib inflation buffer.

lib/png.c, src/png2swf.c
Strict Bpp verify checking for PNG specifications.
This PR resolves the following issue:
- A heapoverflow bug of png2swf.
- https://github.com/matthiaskramm/swftools/issues/50
=> Strict Bpp verify checking for PNG specifications.

config.h.in
In config.h.in, undef boolean/FALSE/TRUE for configure rules.
This is additional PR.
ref)  https://github.com/matthiaskramm/swftools/pull/67
I committed with this.
```
/* Define to `int' if <sys/types.h> does not define. */
#undef boolean
/* boolean constant false */
#undef FALSE
/* boolean constant true */
#undef TRUE
```
Looking at the surrounding code, the following may be better.
```
/* Define to `int' if <sys/types.h> does not define. */
#undef boolean
#undef FALSE
#undef TRUE
```
=> undef boolean/FALSE/TRUE in config.h.in for configure rules.

lib/wav.c, src/swfc.c, src/wav2swf.c
- Fixed a bug that wav_convert2mono underestimates dest->data size.
- Added handling of caller when wav_convert2mono abnormally terminate.
ref) https://github.com/matthiaskramm/swftools/issues/47
Note that PCM formats that do not compress in the time direction, such as alaw, are processed as before, and SWFs with strange sounds are generated.
(Because there may be such demand)
If malloc returns 0, wav_convert2mono returns 0, but the caller was not handling it.
This fix was required in issues/47, but also resolves issues/52.
ref) https://github.com/matthiaskramm/swftools/issues/52
=> fixing to wav_convert2mono  dest->data heapoverflow bug & absence of caller error handling

lib/wav.c
Make sure src->align is non-zero.
Avoid div 0 of align as denominator in samplelen calculation.
ref) https://github.com/matthiaskramm/swftools/issues/57
=> Avoid div 0 of src->align as denominator in samplelen calculation. 

lib/png.c, src/png2swf.c, src/swfc.c
I made the following fixes to png_load function.
- fix to memory leak
- https://github.com/matthiaskramm/swftools/issues/49
- guard from redundant tRNS
- malloc NULL check
- https://github.com/matthiaskramm/swftools/issues/51
- fix to tRNS heap overflow in mode 0, 2
- (maybe not assigned to issues.)
- retval checking & abend processing.
- caller of  png_read_header
- caller of png_load (png2swf, swfc)
The  mode:2(RGB24) tRNS palette processing is incorrect.
It's not a degrade. that has existed before.
| PNG | SWF( screenshot) |
|---|---|
| ![Opaopa-png24-trns](https://user-images.githubusercontent.com/26040/72748001-80adf100-3bf9-11ea-8489-fd39cc27fd93.png) | <img width="120" alt="output.swf.png" src="https://user-images.githubusercontent.com/26040/72748032-94f1ee00-3bf9-11ea-9d5b-4ea44e4c …
=> fixing to png_load vulnerability

lib/pdf/Makefile.in
Compile popplercompat.cc using the C++ compiler, not the C compiler.
Extract commits from https://github.com/matthiaskramm/swftools/pull/44
```
% git cherry-pick 50914eb2ded1f05eb6387460714a8aa30893e810
```
=> Compile popplercompat.cc using the C++ compiler, not the C compiler.

configure.in
C compiler supports -Wimplicit in but not C++
Removed warnings by splitting compiler flags between C and C++
(-Wimplicit flag not legal in C++)
Extract commits from https://github.com/matthiaskramm/swftools/pull/44
```
% git cherry-pick 9c9ff2f77e032b1ccbe80caa9edd5d3f3a20d94b
```
=> C compiler supports -Wimplicit in but not C++

lib/devices/record.c
Fixed warning due to missing gfxdevice_dummy_init declaration.
Extract commits from https://github.com/matthiaskramm/swftools/pull/44
```
% git cherry-pick 039e0563af263d258411c000697694eb63a7457d
```
=> Fixed warning due to missing gfxdevice_dummy_init declaration.

lib/pdf/xpdf-changes.patch
bugfix: character existence check of pos1, pos2 which is the return value of strrchr.
patch file for lib/pdf/xpdf/GlobalParams.cc
This bug cause errors when compiling on macOS.
- macOS Catalina 10.15.2
- Xcode 11.1
- cc Apple clang version 11.0.0
```
xpdf/GlobalParams.cc:925:12: error: ordered comparison between pointer and zero
('char *' and 'int')
if(pos1>=0)
~~~~^ ~
xpdf/GlobalParams.cc:927:17: error: ordered comparison between pointer and zero
('char *' and 'int')
else if(pos2>=0)
```
=> bugfix: character existence check of pos1, pos2

src/gif2swf.c
- EGifCloseFile, DGifCloseFile API changed destructively in giflib-5.1.0
- PrintGifError only works with libungif-4.x.x
- GifErrorString argument added in giflib-5.0.0
ref) https://github.com/matthiaskramm/swftools/pull/2/files
=> I want git2swf to work before giflib-5.1.0.

src/swfextract.c
Sometimes the jpeg app0 header is in the second part of the definebitsjpeg2 tag data, most applications can't handle that. Move it to the start when extracting.
(I accidentally created a broken pull request earlier, sorry about that)
[example-swf.zip](https://github.com/matthiaskramm/swftools/files/4534913/example-swf.zip)
=> swfextract: move jpeg app0 to start of file (fixed)

lib/modules/swfobject.c, lib/modules/swftools.c, src/swfdump.c
Swftools deviates from the [official swf specification](https://wwwimages2.adobe.com/content/dam/acom/en/devnet/pdf/swf-file-format-spec.pdf). This deviation causes Flash to misinterpret some of the swf files generated by swfc.
From PLACEOBJECT2 section:
The specification states, that ClipDepth field comes after the Name field. 
This has been in the code for 15 years according to git blame:
https://github.com/matthiaskramm/swftools/commit/d193d733dfa41679452284e4e60e7237ac721cba#diff-b0ead3b01c9deed99d0df1f51970d65cR124
Here is a swfc script which demonstrates an issue caused by this difference:
```
.flash
.circle cg 200 fill=green line=1
.circle cb 200 fill=blue line=1
.circle cr 200 fill=red line=1
.startclip cg x=0 y=0
.put cb x=0 y=200
.end
.put cr y=0 x=200
.end
```
The problem is, …
=> Fix Name and ClipDepth order

lib/as3/registry.h, src/swfc-feedback.h, src/swfc-history.h
I was getting the following errors when compiling with gcc 10
```
gcc -DHAVE_CONFIG_H parser.o swfc.o swfc-feedback.o swfc-history.o swfc-interpolation.o -o swfc ../lib/librfxswf.a ../lib/libbase.a -L/usr/local/lib -lz -lm 
/usr/bin/ld: swfc-feedback.o:(.bss+0x8): multiple definition of `column'; swfc.o:(.bss+0x38): first defined here
/usr/bin/ld: swfc-feedback.o:(.bss+0xc): multiple definition of `line'; swfc.o:(.bss+0x3c): first defined here
/usr/bin/ld: swfc-feedback.o:(.bss+0x10): multiple definition of `filename'; swfc.o:(.bss+0x40): first defined here
/usr/bin/ld: swfc-feedback.o:(.bss+0x0): multiple definition of `cleanUp'; swfc.o:(.bss+0x30): first defined here
/usr/bin/ld: swfc-history.o:(.bss+0x18): multiple definition of `noBlur'; swfc.o:(.bss+0x20): first defined here …
```
=> Fix double definition linker errors by marking variables as extern
